### PR TITLE
[netlib] Reorganize the architecture

### PR DESCRIPTION
**Pull request by Sigma711**
### Purpose

- Reorganize the architecture of the project directories.
- Classify the modules by their classes.

### Changes

- Create a `server` directory in `src` directory and put `src/netlib` directory into it.
- Create a `util` directory in `src/server` and put `src/netlib/non_copyable_movable.h` into it.

### Review Instructions

- Review `src/server/netlib` and `src/server/util`.

### CODE REVIEW

**Review by L-Super — COMMENTED** [review]
Let me have a look.

**Review by L-Super — APPROVED** [review]
LGTM

**Review by renph — APPROVED** [review]
LGTM

**Review by million-2002 — COMMENTED** [review]
Let me have a look.

**Review by million-2002 — APPROVED** [review]
SGTM

**Review by Sigma711 — COMMENTED** [review]
@maxlv7 Please review it for me and approve if nothing wrong.

**Review by mayfly227 — APPROVED** [review]
LGTM

**Pull request merged**
